var md_docpages_03_example_programs =
[
    [ "Creating Your First Bot", "firstbot.html", null ],
    [ "Using Slash Commands and Interactions", "slashcommands.html", null ],
    [ "Creating a Sound Board", "soundboard.html", null ],
    [ "Streaming Ogg Opus file", "oggopus.html", null ],
    [ "Streaming MP3 files", "stream-mp3-discord-bot.html", null ],
    [ "Record yourself in a VC", "record-user.html", null ],
    [ "Join or switch to the voice channel of the user issuing a command", "joinvc.html", null ],
    [ "Integrating with spdlog", "spdlog.html", null ],
    [ "Using component interactions (buttons)", "components.html", null ],
    [ "Using component interactions (select menus)", "components3.html", null ],
    [ "Using component interactions (advanced)", "components2.html", null ],
    [ "Modal Dialog Interactions", "modal-dialog-interactions.html", null ],
    [ "Using a command handler object", "commandhandler.html", null ],
    [ "Using sub-commands in slash commands", "subcommands.html", null ],
    [ "Sending Embeds", "embed-message.html", null ],
    [ "Slash command auto completion", "application-command-autocomplete.html", null ],
    [ "Attaching a file to a message", "attach-file.html", null ],
    [ "Caching Messages", "caching-messages.html", null ],
    [ "Collecting Reactions", "collecting-reactions.html", null ],
    [ "Context Menus", "context-menu.html", null ],
    [ "Webhooks", "webhooks.html", null ],
    [ "Making an eval command in C++", "cpp-eval-command-discord.html", null ],
    [ "Using file parameters for application commands (slash commands)", "discord-application-command-file-upload.html", null ]
];